version: '2.4'
services:
  app:
    container_name: yellow-app
    mem_limit: 1024m
    mem_reservation: 300m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    build:
      context: ./docker
    ports:
      - 80:80
    volumes:
      - ./:/app:delegated
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    depends_on:
      - db
  db:
    container_name: yellow-db
    image: postgres
    environment:
      POSTGRES_DB: yellow
      POSTGRES_USER: yellow
      POSTGRES_PASSWORD: yellow
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
